
# Loop constraints
directive set /filter/core/core:rlp CSTEPS_FROM {{. == 1}}
directive set /filter/core/core:rlp/buffer:buf:vinit CSTEPS_FROM {{. == 2} {.. == 1}}
directive set /filter/core/core:rlp/main CSTEPS_FROM {{. == 6} {.. == 1}}

# IO operation constraints
directive set /filter/core/core:rlp/main/else:io_read(in_data_vld:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/pixel_processing:io_read(in_data:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/pixel_processing:if:io_write(out_data:rsc.@) CSTEPS_FROM {{.. == 4}}

# Sync operation constraints

# Real operation constraints
directive set /filter/core/core:rlp/buffer:buf:vinit/buffer:buf:write_mem(buffer:buf:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/buffer:buf:vinit/buffer:buf:acc CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/if:if:read_mem(mcu_data:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /filter/core/core:rlp/main/if:if:write_mem(mcu_data:rsc.@) CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/if:if:write_mem(mcu_data:rsc.@)#1 CSTEPS_FROM {{.. == 4}}
directive set /filter/core/core:rlp/main/buffer:mux CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/buffer:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/buffer:read_mem(buffer:buf:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /filter/core/core:rlp/main/buffer:read_mem(buffer:buf:rsc.@)#1 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/buffer:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/buffer:write_mem(buffer:buf:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /filter/core/core:rlp/main/buffer:mux#1 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/buffer:mux#2 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/system_input:if#1:qelse:acc CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/system_input:if#1:system_input:if#1:and#1 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/system_input:if#2:qelse:acc CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/system_input:if#2:system_input:if#2:and CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/system_input:else#2:acc CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/system_input:system_input:and#1 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/clip_window:switch-lp#3:mux1h CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/clip_window:switch-lp#2:mux1h CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/clip_window:switch-lp#1:mux1h CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/clip_window:switch-lp:mux1h CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/clip_window:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/clip_window:mux#2 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/clip_window:mux CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:if:acc CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/clip_window:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:if:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux#4 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux#5 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:if:acc#3 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#6 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#7 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:if:acc CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1b:mux CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1b:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1b:if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1b:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1b:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1b:if:acc#2 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#4 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#5 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux#8 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux#10 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:if:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux#11 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux#12 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:if:acc#6 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#13 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#14 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:if:acc#7 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#15 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#16 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:if:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1b:mux#6 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1b:mux#7 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1b:if:acc#4 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#8 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#9 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:if:acc#5 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#10 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#11 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:if:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:mux#17 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/L1a:if:acc#9 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#18 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#19 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:if:acc#10 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#20 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#21 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:if:acc#11 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#22 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#23 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:if:acc#6 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#12 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:if:acc#7 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#13 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#14 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:if:acc#8 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#15 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#16 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:if:acc#12 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#24 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#25 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:if:acc#13 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#26 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#27 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:if:acc#14 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:mux#28 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:if:acc#9 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#17 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:if:acc#10 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#18 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#19 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:if:acc#11 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1b:mux#20 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/L1a:if:acc#15 CSTEPS_FROM {{.. == 4}}
directive set /filter/core/core:rlp/main/L1a:mux#29 CSTEPS_FROM {{.. == 4}}
directive set /filter/core/core:rlp/main/L1a:if:acc#16 CSTEPS_FROM {{.. == 4}}
directive set /filter/core/core:rlp/main/L1a:mux#30 CSTEPS_FROM {{.. == 4}}
directive set /filter/core/core:rlp/main/L1b:if:acc#12 CSTEPS_FROM {{.. == 4}}
directive set /filter/core/core:rlp/main/L1b:mux#21 CSTEPS_FROM {{.. == 4}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if:acc CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if:read_mem(mcu_data:rsc.@) CSTEPS_FROM {{.. == 4}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if:pixel_processing:if:if:acc#1 CSTEPS_FROM {{.. == 5}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if:write_mem(mcu_data:rsc.@) CSTEPS_FROM {{.. == 5}}
directive set /filter/core/core:rlp/main/thresholding:acc CSTEPS_FROM {{.. == 4}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if#1:if:read_mem(mcu_data:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if#1:write_mem(mcu_data:rsc.@) CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/pixel_processing:if:if#1:acc CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#1 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/mux#2 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#8 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#9 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#10 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#11 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#12 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#13 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#14 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#15 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/mux#16 CSTEPS_FROM {{.. == 3}}
directive set /filter/core/core:rlp/main/mux#17 CSTEPS_FROM {{.. == 2}}
directive set /filter/core/core:rlp/main/else:mux#47 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#48 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/else:mux#48 CSTEPS_FROM {{.. == 1}}
directive set /filter/core/core:rlp/main/mux#49 CSTEPS_FROM {{.. == 1}}

# Probe constraints
