directive set /filter/filter:core/filter:core:conc/thresholding:acc RESOURCE_NAME L1a:if:acc#14:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#8 RESOURCE_NAME L1a:if:acc#14:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#14 RESOURCE_NAME L1a:if:acc#14:rg
directive set /filter/filter:core/filter:core:conc/L1b:if:acc#6 RESOURCE_NAME L1b:if:acc#12:rg
directive set /filter/filter:core/filter:core:conc/L1b:if:acc#12 RESOURCE_NAME L1b:if:acc#12:rg
directive set /filter/filter:core/filter:core:conc/L1b:if:acc#3 RESOURCE_NAME L1b:if:acc#12:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#16 RESOURCE_NAME L1a:if:acc#16:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#2 RESOURCE_NAME L1a:if:acc#16:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#7 RESOURCE_NAME L1a:if:acc#16:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#15 RESOURCE_NAME L1a:if:acc:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc RESOURCE_NAME L1a:if:acc:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#6 RESOURCE_NAME L1a:if:acc:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#1 RESOURCE_NAME L1a:if:acc#1:rg
directive set /filter/filter:core/filter:core:conc/L1b:if:acc#2 RESOURCE_NAME L1a:if:acc#1:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#5 RESOURCE_NAME L1a:if:acc#10:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#10 RESOURCE_NAME L1a:if:acc#10:rg
directive set /filter/filter:core/filter:core:conc/L1b:if:acc#1 RESOURCE_NAME L1b:if:acc#1:rg
directive set /filter/filter:core/filter:core:conc/L1b:if:acc#4 RESOURCE_NAME L1b:if:acc#1:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#4 RESOURCE_NAME L1a:if:acc#4:rg
directive set /filter/filter:core/filter:core:conc/L1a:if:acc#9 RESOURCE_NAME L1a:if:acc#4:rg
directive set /filter/filter:core/filter:core:conc/L1b:if:acc RESOURCE_NAME L1b:if:acc:rg
directive set /filter/filter:core/filter:core:conc/L1b:if:acc#5 RESOURCE_NAME L1b:if:acc:rg
